kind: Service
apiVersion: v1
metadata:
  name: flb-chatops
  labels:
    app: flb-chatops
spec:
  type: NodePort
  selector:
    app: flb-chatops
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: flb-chatops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flb-chatops
  template:
    metadata:
      labels:
        app: flb-chatops
        version: v1
    spec:
      containers:
      - name: flb-chatops
        image: flb-chatops
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
