version: '2'

services:
  fluent-bit:
    image: fluent/fluent-bit:2.2.2
    ports:
      # HTTP server communication
      - 8090:8090
      # Inject alerts via HTTP
      - 8095:8095
    volumes:
      - ./fluent-bit-config:/fluent-bit/etc/
    tmpfs: /logs
    env_file: .env
    environment:
      FB_CONFIG_DIR: /fluent-bit/etc/
      LOG_DIR: /logs/
      CHAT_OPS_SVR: http-slack-server
      CHAT_OPS_PORT: '8080'
      DUMMY_MESSAGE: 'Alert from Pat'

  http-slack-server:
    build: ./Dockerfile
    ports:
      - 8080:8080
    env_file: .env
